MvcProjeKampi/Controllers/WriterPanelController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataAccessLayer.Concrete;
using EntityLayer.Concrete;

namespace MvcProjeKampi.Controllers
{
    public class WriterPanelController : Controller
    {
        // GET: WriterPanel
        private HeadingManager hm = new HeadingManager(new EfHeadingDal());
        private CategoryManager cm = new CategoryManager(new EfCategoryDal());
        
        public ActionResult WriterProfile()
        {
            return View();
        }

        [AllowAnonymous]
        public ActionResult MyHeading(string p)
        {
            Context c = new Context();
            p = (string) Session["WriterMail"];
            var writeridinfo = c.Writers.Where(x => x.WriterMail == p).Select(y => y.WriterID).FirstOrDefault();
            var values = hm.GetListByWriter(writeridinfo);
            return View(values);
        }
        
        [HttpGet]
        public ActionResult NewHeading()
        {
            List<SelectListItem> valuecategory = (from x in cm.GetList()
                select new SelectListItem
                {
                    Text = x.CategoryName,
                    Value = x.CategoryID.ToString()
                }).ToList();
            ViewBag.vlc = valuecategory;
            return View();
        }

        [HttpPost]
        public ActionResult NewHeading(Heading p)
        {
            p.HeadingDate = DateTime.Parse(DateTime.Now.ToShortDateString());
            p.WriterID = 4;
            p.HeadingStatus = true;
            hm.HeadingAdd(p);
            return RedirectToAction("MyHeading");
        }

        [HttpGet]
        public ActionResult EditHeading(int id)
        {
            List<SelectListItem> valuecategory = (from x in cm.GetList()
                select new SelectListItem
                {
                    Text = x.CategoryName,
                    Value = x.CategoryID.ToString()
                }).ToList();
            ViewBag.vlc = valuecategory;
            var HeadingValue = hm.GetByID(id);
            return View(HeadingValue);
        }

        [HttpPost]
        public ActionResult EditHeading(Heading p)
        {
            hm.HeadingUpdate(p);
            return RedirectToAction("MyHeading");
        }

        public ActionResult DeleteHeading(int id)
        {
            var headingValue = hm.GetByID(id);
            headingValue.HeadingStatus = false;
            hm.HeadingDelete(headingValue);
            return RedirectToAction("MyHeading");
        }
    }
}

MvcProjeKampi/Views/WriterPanel/EditHeading.cshtml
@model EntityLayer.Concrete.Heading

@{
    ViewBag.Title = "EditHeading";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<h2>Başlık Güncelleme Sayfası</h2>
@using (Html.BeginForm("EditHeading", "WriterPanel", FormMethod.Post))
{
    <div class="form-group">
        @Html.HiddenFor(x => x.HeadingID)
        @Html.HiddenFor(x => x.HeadingDate)
        @Html.HiddenFor(x => x.WriterID)
        @Html.Label("Başlık Adı")
        @Html.TextBoxFor(x => x.HeadingName, new { @class = "form-control" })
        <br />
        @Html.Label("Kategori")
        @Html.DropDownListFor(x => x.CategoryID, (List<SelectListItem>)ViewBag.vlc, new { @class = "form-control" })
        <br />
        <button class="btn btn-success">Güncelle</button>

    </div>
}

MvcProjeKampi/Views/WriterPanel/MyHeading.cshtml
@using EntityLayer.Concrete
@model List<Heading>
@{
    ViewBag.Title = "MyHeading";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

@{ string color = "";}
@{ string delete = "";}
@{ string deleteName = "";}

<!DOCTYPE html>
<html>

<body class="hold-transition sidebar-mini">



    <!-- Main content -->
    <section class="content">

        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Başlık İşlemleri</h3>

                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                        <i class="fas fa-times"></i>
                    </button>
                </div>
            </div>
            <div class="card-body p-0">
                <table class="table table-striped projects">
                    <thead>
                        <tr>
                            <th style="width: 1%">
                                #
                            </th>
                            <th style="width: 18%">
                                Başlık Adı
                            </th>
                            <th style="width: 11%" class="text-center">
                                Oluşturan Yazar
                            </th>
                            <th style="width: 8%" class="text-center">
                                Kategori
                            </th>
                            <th style="width: 25%">
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            if (item.Category.CategoryName == "Tiyatro")
                            {
                                color = "badge badge-warning";
                            }
                            if (item.Category.CategoryName == "Spor")
                            {
                                color = "badge badge-success";
                            }
                            if (item.Category.CategoryName == "Yazılım")
                            {
                                color = "badge badge-info";
                            }
                            if (item.Category.CategoryName == "Seyahat")
                            {
                                color = "badge badge-secondary";
                            }
                            if (item.Category.CategoryName == "Dizi")
                            {
                                color = "badge badge-primary";
                            }
                            if (item.Category.CategoryName == "Film")
                            {
                                color = "badge badge-danger";
                            }
                            if (item.Category.CategoryName == "Kitap")
                            {
                                color = "badge badge-dark";
                            }
                            if (item.Category.CategoryName == "Sosyal Medyalar")
                            {
                                color = "badge badge-info";
                            }
                            if (item.Category.CategoryName == "Eğitim")
                            {
                                color = "badge badge-light";
                            }


                            <tr>
                                <td>
                                    @item.HeadingID
                                </td>
                                <td>
                                    <a>
                                        @item.HeadingName
                                    </a>
                                    <br />
                                    <small>
                                        @(((DateTime)item.HeadingDate).ToString("dd - MMM - yyyy"))
                                    </small>
                                </td>
                                <td class="text-center">
                                    <ul class="list-inline">
                                        <li class="list-inline-item">
                                            <img alt="Avatar" class="table-avatar" src="@item.Writer.WriterImage">
                                        </li>
                                    </ul>
                                </td>
                                <td class="project-state">
                                    <span class="@color">@item.Category.CategoryName</span>
                                </td>
                                <td class="project-actions text-right">
                                    <a class="btn btn-primary btn-sm" href="/Content/ContentByHeading/@item.HeadingID">
                                        <i class="fas fa-folder">
                                        </i>
                                        Yazılar
                                    </a>
                                    <a class="btn btn-info btn-sm" href="/WriterPanel/EditHeading/@item.HeadingID">
                                        <i class="fas fa-pencil-alt">
                                        </i>
                                        Düzenle
                                    </a>
                                    <a class="btn btn-danger btn-sm" href="/WriterPanel/DeleteHeading/@item.HeadingID">
                                        <i class="fas fa-trash">
                                        </i>
                                        Sil
                                    </a>
                                </td>
                            </tr>
                        }

                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->

    </section>

</body>
</html>
<a href="/WriterPanel/NewHeading/" class="btn btn-primary">Yeni Başlık Girişi</a>

MvcProjeKampi/Views/WriterPanel/NewHeading.cshtml
@model EntityLayer.Concrete.Heading
@{
    ViewBag.Title = "NewHeading";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<h1>Yeni Başlık Ekleme</h1>
<br />
@using (Html.BeginForm("NewHeading", "WriterPanel", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Başlık Adı")
        @Html.TextBoxFor(x => x.HeadingName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.HeadingName)
        <br />
        @Html.Label("Kategori")
        @Html.DropDownListFor(x => x.CategoryID, (List<SelectListItem>)ViewBag.vlc, new { @class = "form-control" })
        <br />

        <button class="btn btn-info">Başlık Oluştur</button>
    </div>
}

MvcProjeKampi/Views/WriterPanel/WriterProfile.cshtml
@{
    ViewBag.Title = "WriterProfile";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<h2>WriterProfile</h2>